apiVersion: v1
kind: ServiceAccount
metadata:
  name: kstat-service-account
  namespace: kstat-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kstat-role
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "nodes/metrics", "services", "endpoints", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics", "/metrics/cadvisor"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kstat-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kstat-role
subjects:
- kind: ServiceAccount
  name: kstat-service-account
  namespace: kstat-system
