apiVersion: v1
kind: ConfigMap
metadata:
  name: kstat-prometheus-configmap
  namespace: kstat-system
data:
  prometheus.yml: |-
    ---
    global:
      scrape_interval: 5s

    scrape_configs:
    - job_name: node-exporter
      #- targets: ["144.126.214.177:9095","144.126.214.226:9095","144.126.222.20:9095"]
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - kstat-system
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_endpoint_node_name
        action: replace
        target_label: instance

