#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p dist/artifacts
cp bin/kstat dist/artifacts/kstat${SUFFIX}

IMAGE=${REPO}/kstat:${TAG}
DOCKERFILE=package/Dockerfile
if [ -e ${DOCKERFILE}.${ARCH} ]; then
    DOCKERFILE=${DOCKERFILE}.${ARCH}
fi

docker build -f ${DOCKERFILE} -t ${IMAGE} .
echo Built ${IMAGE}

files=`find ./deploy/ |grep yaml |sort`
rm -f ./dist/kstat.yaml
for f in $files
do
	echo $f
	cat $f >> ./dist/kstat.yaml
	echo --- >> ./dist/kstat.yaml
done
echo Updated kstat.yaml
